### ISSUE TITLE
Add tk-multi-reviewsubmission2 to configuration

### ISSUE THREAD

**Issue by MaximumFX** [nfa-vfxim/nfa-shotgun-configuration#107]
Add [tk-multi-reviewsubmission2](https://github.com/MaximumFX/tk-multi-reviewsubmission2) to the NFA ShotGrid Configuration.

**Comment by gillesvink** [comment]
It would be great if we would merge your branch into the original branch. That would be better for maintainability so we keep all our repos at the nfa-vfxim organization

**Comment by MaximumFX** [comment]
I completely rewrote the app from scratch and it's more of a replacement/new app than a new version. Still wanted to go over the original app and see if it is currently being used at all.
